name: clean_architecture_todo_app
description: CleanArchitecuture ToDo App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  path: ^1.8.2
  sqflite: ^2.2.2
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  mockito: ^5.3.2

flutter:
  uses-material-design: true
