name: clean_architecture_todo_app
description: CleanArchitecuture ToDo App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.14.0+3
  freezed_annotation: ^0.14.2
  rxdart: ^0.27.1
  sqflite: ^2.0.0+3
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.2
  mockito: ^5.0.10

flutter:
  uses-material-design: true
